version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: lukovsk
      POSTGRES_PASSWORD: 3569

  flask_app:
    build: .
    ports: 
      - 5000:5000
    depends_on:
      - db

volumes:
  postgres_data: